open Types

(* function generated by chat gpt, temporary *)
let string_of_signal (m : Bool3.t FloatMap.t) : string =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "{\n";

  FloatMap.iter
    (fun t_inner b ->
       Buffer.add_string buffer ("  " ^ string_of_float t_inner ^ " -> " 
               ^ Bool3.to_string b ^ "\n"))
    m;

  Buffer.add_string buffer "}";
  Buffer.contents buffer

(* function generated by chat gpt, temporary *)
let string_of_signal_signal (m : Bool3.t FloatMap.t FloatMap.t) : string =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "{\n";

  FloatMap.iter
    (fun t_inner inner_map ->
       Buffer.add_string buffer ("  " ^ string_of_float t_inner ^ " -> {\n");
       FloatMap.iter
         (fun t value ->
            Buffer.add_string buffer
              ("    "
               ^ string_of_float t
               ^ " -> "
               ^ Bool3.to_string value
               ^ "\n"))
         inner_map;

       Buffer.add_string buffer "  }\n")
    m;

  Buffer.add_string buffer "}";
  Buffer.contents buffer

  (*Also chat gpt*)
let string_of_string_set_between_signal
  (m : (AgentSet.t between) FloatMap.t FloatMap.t)
  : string =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "{\n";

  FloatMap.iter
    (fun t_outer inner_map ->
       Buffer.add_string buffer
         ("  " ^ string_of_float t_outer ^ " -> {\n");

       FloatMap.iter
         (fun t_inner (Between (lower, upper)) ->
            let string_of_set s =
              "{"
              ^ (String.concat ", "
                   (AgentSet.elements s))
              ^ "}"
            in

            Buffer.add_string buffer
              ("    "
               ^ string_of_float t_inner
               ^ " -> Between("
               ^ string_of_set lower
               ^ ", "
               ^ string_of_set upper
               ^ ")\n"))
         inner_map;

       Buffer.add_string buffer "  }\n")
    m;

  Buffer.add_string buffer "}";
  Buffer.contents buffer



let string_of_string_set_between_signal_sh
  (m : (AgentSet.t between) FloatMap.t FloatMap.t FloatMap.t)
  : string =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "{\n";

  FloatMap.iter
    (fun t_outer middle_map ->
       Buffer.add_string buffer
         ("  " ^ string_of_float t_outer ^ " -> {\n");

       FloatMap.iter
         (fun t_mid inner_map ->
            Buffer.add_string buffer
              ("    " ^ string_of_float t_mid ^ " -> {\n");

            FloatMap.iter
              (fun t_inner (Between (lower, upper)) ->
                 let string_of_set s =
                   "{"
                   ^ (String.concat ", " (AgentSet.elements s))
                   ^ "}"
                 in

                 Buffer.add_string buffer
                   ("      "
                    ^ string_of_float t_inner
                    ^ " -> Between("
                    ^ string_of_set lower
                    ^ ", "
                    ^ string_of_set upper
                    ^ ")\n"))
              inner_map;

            Buffer.add_string buffer "    }\n")
         middle_map;

       Buffer.add_string buffer "  }\n")
    m;

  Buffer.add_string buffer "}";
  Buffer.contents buffer


let hmap_tostring
  (m : (AgentSet.t between) FloatMap.t)
  : string =
  let buffer = Buffer.create 256 in
  Buffer.add_string buffer "{\n";

  FloatMap.iter
    (fun t (Between (lower, upper)) ->
       let string_of_set s =
         "{"
         ^ String.concat ", " (AgentSet.elements s)
         ^ "}"
       in

       Buffer.add_string buffer
         ("  "
          ^ string_of_float t
          ^ " -> Between("
          ^ string_of_set lower
          ^ ", "
          ^ string_of_set upper
          ^ ")\n"))
    m;

  Buffer.add_string buffer "}";
  Buffer.contents buffer